language: python
python:
  - "2.7.11"
install:
  - pip install -r requirements/test.txt
  - pip install coveralls
script:
  - python manage.py migrate --noinput
  - python manage.py loaddata states.json
  - coverage run manage.py test --verbosity 3
after_success:
  - coveralls

