language: python
python:
  - "2.6"
install:
  - pip install -r requirements.txt
script:
  - cd oahapi/oahapi/settings
  - cp local_settings.py.sample local_settings.py
  - cd ../..
  - python manage.py test
