language: python
python:
- 3.6
install:
- pip install tox-travis
script:
- tox
- python setup.py bdist_wheel
after_success:
- coveralls
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JSajnwpeUixOaWnQzaQCmeg9/74h/QKFtz7difgKuUg7SmuY462Jyr2mkTQkYQWPR28lqB/pIp7DlTjrN9inxpdtVpsm0RSgvuzvW7ZmlWr2xLb6wjHMArtRVJsdqODauQa9EH2ArqeKvXrCqWP2LQI6RFgoElOH3ilcemElj+w=
  file_glob: true
  file: dist/*.whl
  on:
    tags: true
